let totCount = 0;
let data = [45, 27, 12, 39, 70, 12, 24, 9, 20, 31, 22, 28];
data.forEach((val) => (totCount += val));

let InnovationKPIData = {
  numberCard: [
    {
      title: "Ideas",
      number: +totCount,
      unit: "",
      lineData: {
        title: "",
        labels: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "June",
          "July",
          "Aug",
          "Sept",
          "Oct",
          "Nov",
          "Dec",
        ],
        data: [45, 27, 12, 39, 70, 12, 24, 9, 20, 31, 22, 28],
      },
    },
    {
      title: "Approved Ideas",
      number: Math.floor(totCount * 0.35),
      unit: "",
      lineData: {
        title: "",
        labels: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "June",
          "July",
          "Aug",
          "Sept",
          "Oct",
          "Nov",
          "Dec",
        ],
        data: [0, 0, 12, 6, 10, 10, 24, 9, 20, 5, 4, 2],
      },
    },
    {
      title: "Ideas Implemented",
      number: Math.floor(totCount * 0.15),
      unit: "",
      lineData: {
        title: "",
        labels: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "June",
          "July",
          "Aug",
          "Sept",
          "Oct",
          "Nov",
          "Dec",
        ],
        data: [2, 4, 6, 0, 7, 12, 0, 0, 2, 5, 6, 6],
      },
    },
    {
      title: "Revene Generated",
      number: 11200,
      unit: "$",
      lineData: {
        title: "",
        labels: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "June",
          "July",
          "Aug",
          "Sept",
          "Oct",
          "Nov",
          "Dec",
        ],
        data: [2, 4, 6, 0, 7, 12, 0, 0, 2, 5, 6, 6],
      },
    },
  ],
  barGraph: {
    title: "Ideas",
    lables: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "June",
      "July",
      "Aug",
      "Sept",
      "Oct",
      "Nov",
      "Dec",
    ],
    data: [45, 27, 12, 39, 70, 12, 24, 9, 20, 31, 22, 28],
  },
  doughnutGraph: {
    labels: ["Approved", "Implemented", "On Hold"],
    data: [118, 50, 171],
  },
  LineGraph: {
    title: "Ideas",
    labels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "June",
      "July",
      "Aug",
      "Sept",
      "Oct",
      "Nov",
      "Dec",
    ],
    data: [45, 27, 12, 39, 70, 12, 24, 9, 20, 31, 22, 28],
  },
};

export default InnovationKPIData;
